"""Deterministic Markdown rendering for validated AI responses.

All model-provided strings are untrusted: they are redacted and escaped
before rendering. Findings are sorted by severity then stable identifier so
re-runs produce identical output for identical input.
"""

from __future__ import annotations

from dataclasses import dataclass

from .config import Settings
from .redaction import redact
from .schemas import (
    MilestoneAuditResponse,
    PRReviewResponse,
    TriageResponse,
)
from .scanner_parser import ScannerFinding

PR_REVIEW_MARKER = "<!-- chateau-ai-contextual-review -->"
TRIAGE_MARKER = "<!-- chateau-ai-security-triage -->"

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}

_ADVISORY = (
    "> :robot: **Advisory output only.** This report was generated by an AI "
    "model and must be verified by a human reviewer. It does not replace or "
    "override pytest, Bandit, Semgrep, pip-audit or OWASP ZAP, and it cannot "
    "approve, merge or suppress anything."
)


@dataclass(frozen=True)
class RenderMeta:
    model: str
    input_tokens: int | None = None
    output_tokens: int | None = None
    truncated: bool = False


def escape_text(text: str) -> str:
    """Neutralise untrusted text for safe Markdown rendering."""
    cleaned = redact(text or "")
    cleaned = cleaned.replace("<", "&lt;").replace(">", "&gt;")
    cleaned = cleaned.replace("|", "&#124;")
    # Break code fences and comment markers that could smuggle markup.
    cleaned = cleaned.replace("```", "`​``")
    return cleaned.strip()


def _footer(meta: RenderMeta) -> str:
    usage = "not reported"
    if meta.input_tokens is not None or meta.output_tokens is not None:
        usage = (
            f"input {meta.input_tokens if meta.input_tokens is not None else '?'}, "
            f"output {meta.output_tokens if meta.output_tokens is not None else '?'}"
        )
    truncation = "yes" if meta.truncated else "no"
    return (
        "\n---\n"
        f"_Model: `{escape_text(meta.model)}` | Token usage: {usage} | "
        f"Context truncated: {truncation}_\n"
    )


def _cap(body: str, settings: Settings) -> str:
    if len(body) <= settings.max_comment_chars:
        return body
    notice = "\n\n> :warning: Report truncated to fit the GitHub comment limit.\n"
    return body[: settings.max_comment_chars - len(notice)] + notice


def _sorted_findings(findings):
    return sorted(
        findings,
        key=lambda f: (_SEVERITY_ORDER.get(f.severity.value, 9), f.id),
    )


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {escape_text(item)}" for item in items) or "- None reported"


def render_pr_review(
    response: PRReviewResponse, meta: RenderMeta, settings: Settings
) -> str:
    lines = [
        PR_REVIEW_MARKER,
        "## AI Contextual PR Review",
        "",
        _ADVISORY,
        "",
        f"**Overall risk:** `{response.overall_risk.value}`",
        "",
        escape_text(response.summary),
        "",
    ]
    if response.findings:
        lines.append(f"### Findings ({len(response.findings)})")
        for finding in _sorted_findings(response.findings):
            lines += [
                "",
                f"#### [{finding.severity.value.upper()}] "
                f"{escape_text(finding.title)} (`{escape_text(finding.id)}`)",
                f"- **Classification:** {finding.classification.value}",
                f"- **Confidence:** {finding.confidence.value}",
                f"- **Files:** {', '.join(f'`{escape_text(p)}`' for p in finding.files) or 'n/a'}",
                f"- **Evidence:** {escape_text(finding.evidence)}",
                f"- **Impact:** {escape_text(finding.impact)}",
                f"- **Recommendation:** {escape_text(finding.recommendation)}",
            ]
            if finding.project_requirements:
                lines.append(
                    "- **Project requirements:** "
                    + ", ".join(escape_text(r) for r in finding.project_requirements)
                )
            if finding.misuse_cases:
                lines.append(
                    "- **Misuse cases:** "
                    + ", ".join(escape_text(m) for m in finding.misuse_cases)
                )
            if finding.stride:
                lines.append(
                    "- **STRIDE:** " + ", ".join(escape_text(s) for s in finding.stride)
                )
            if finding.owasp_mapping:
                lines.append(
                    "- **OWASP:** "
                    + ", ".join(escape_text(o) for o in finding.owasp_mapping)
                )
            if finding.suggested_tests:
                lines.append("- **Suggested tests:**")
                lines += [
                    f"  - {escape_text(t)}" for t in finding.suggested_tests
                ]
    else:
        lines.append("### Findings\n\nNo supported findings in the reviewed diff.")
    lines += [
        "",
        "### Positive controls observed",
        _bullets(response.positive_controls),
        "",
        "### Insufficient evidence",
        _bullets(response.insufficient_evidence),
    ]
    if response.truncated or meta.truncated:
        lines += [
            "",
            "> :warning: The review context was truncated. Unreviewed content "
            "was **not** assessed.",
        ]
    return _cap("\n".join(lines) + _footer(meta), settings)


_VERDICT_LABEL = {
    "likely_true_positive": ":red_circle: likely true positive",
    "likely_false_positive": ":white_circle: likely false positive (still requires human confirmation; not suppressed)",
    "needs_investigation": ":orange_circle: needs investigation",
}


def render_triage(
    findings: list[ScannerFinding],
    response: TriageResponse | None,
    meta: RenderMeta,
    settings: Settings,
) -> str:
    lines = [
        TRIAGE_MARKER,
        "## AI Security Scan Triage",
        "",
        _ADVISORY,
        "",
        "> Scanner results remain authoritative. No finding is suppressed or "
        "resolved by this triage.",
        "",
    ]
    if not findings:
        lines += ["**No scanner findings were reported.** No AI call was made."]
        return _cap("\n".join(lines) + _footer(meta), settings)

    assessments = {}
    if response is not None:
        lines += [escape_text(response.summary), ""]
        assessments = {a.finding_id: a for a in response.assessments}

    group_seen: dict[str, list[str]] = {}
    for finding in findings:
        group_seen.setdefault(finding.group_key, []).append(finding.finding_id)

    lines.append(f"### Findings ({len(findings)})")
    for finding in sorted(
        findings,
        key=lambda f: (_SEVERITY_ORDER.get(f.severity, 9), f.finding_id),
    ):
        location = f"`{escape_text(finding.path)}`"
        if finding.line:
            location += f" line {finding.line}"
        lines += [
            "",
            f"#### `{finding.finding_id}` — {escape_text(finding.rule_id)}",
            f"- **Scanner:** {escape_text(finding.scanner)}",
            f"- **Original severity:** {escape_text(finding.severity)}",
            f"- **Location:** {location}",
            f"- **Scanner message:** {escape_text(finding.message)}",
        ]
        duplicates = [i for i in group_seen[finding.group_key] if i != finding.finding_id]
        if duplicates:
            lines.append(
                "- **Duplicate group:** same rule/file as "
                + ", ".join(f"`{d}`" for d in duplicates)
            )
        assessment = assessments.get(finding.finding_id)
        if assessment is None:
            lines.append("- **AI triage:** not assessed (treat as needs investigation)")
            continue
        lines += [
            f"- **AI triage:** {_VERDICT_LABEL[assessment.verdict.value]} "
            f"(confidence: {assessment.confidence.value})",
            f"- **Application impact:** {escape_text(assessment.application_impact)}",
            f"- **Investigate:** {escape_text(assessment.recommended_investigation)}",
            f"- **Remediate:** {escape_text(assessment.recommended_remediation)}",
            f"- **Regression test:** {escape_text(assessment.suggested_regression_test)}",
        ]
        for label, values in (
            ("Project requirements", assessment.project_requirements),
            ("OWASP", assessment.owasp_mapping),
            ("NIST", assessment.nist_relevance),
            ("OSA", assessment.osa_classification),
        ):
            if values:
                lines.append(
                    f"- **{label}:** " + ", ".join(escape_text(v) for v in values)
                )
    if response is not None and response.insufficient_evidence:
        lines += ["", "### Insufficient evidence", _bullets(response.insufficient_evidence)]
    if response is not None and (response.truncated or meta.truncated):
        lines += ["", "> :warning: Triage context was truncated."]
    return _cap("\n".join(lines) + _footer(meta), settings)


def render_milestone_audit(
    response: MilestoneAuditResponse, meta: RenderMeta, settings: Settings, scope: str
) -> str:
    lines = [
        "# AI Milestone Consistency Audit",
        "",
        _ADVISORY,
        "",
        f"**Scope:** `{escape_text(scope)}`",
        "",
        "## 1. Executive summary",
        "",
        escape_text(response.executive_summary),
        "",
    ]
    sections: dict[str, list] = {}
    for item in response.items:
        sections.setdefault(item.section, []).append(item)
    for section in sorted(sections):
        lines += ["", f"## {escape_text(section)}"]
        for item in sorted(
            sections[section],
            key=lambda i: (_SEVERITY_ORDER.get(i.severity.value, 9), i.id),
        ):
            lines += [
                "",
                f"### [{item.classification.value}] "
                f"{escape_text(item.title)} (`{escape_text(item.id)}`)",
                f"- **Severity:** {item.severity.value}",
                f"- **Detail:** {escape_text(item.detail)}",
                f"- **Evidence:** {escape_text(item.evidence)}",
                f"- **Recommendation:** {escape_text(item.recommendation)}",
            ]
            if item.project_requirements:
                lines.append(
                    "- **Project requirements:** "
                    + ", ".join(escape_text(r) for r in item.project_requirements)
                )
    lines += [
        "",
        "## Prioritised actions before code freeze",
        _bullets(response.prioritised_actions),
        "",
        "## Insufficient-evidence areas",
        _bullets(response.insufficient_evidence),
    ]
    if response.truncated or meta.truncated:
        lines += ["", "> :warning: Audit context was truncated."]
    return _cap("\n".join(lines) + _footer(meta), settings)
